### ISSUE TITLE
there many transform method in dataset.py

### ISSUE THREAD

**Issue by SkyWalker2099** [mhw32/contrastive-ring-public#1]
what determines which transform method we should choose,  and should i use a transform method in test.

**Comment by mhw32** [comment]
I think if you are using MoCo-V2, you should use `mocov2_transforms` or variants of that depending on pixel size. Otherwise, I would just use `load_default_transforms`. See `get_datasets` in `https://github.com/mhw32/contrastive-ring-public/blob/main/src/datasets/datasets.py`. 

More generally, the right transforms really depend on your application. The default transforms are good for cifar or imagenet but may not be good for other applications.

**Comment by SkyWalker2099** [comment]
ok, i got it, thanks


 
---Original---
From: "Mike ***@***.***&gt;
Date: 2021/11/20 04:50:45
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mhw32/contrastive-ring-public] there many transform method indataset.py (Issue #1)




 
I think if you are using MoCo-V2, you should use mocov2_transforms or variants of that depending on pixel size. Otherwise, I would just use load_default_transforms. See get_datasets in https://github.com/mhw32/contrastive-ring-public/blob/main/src/datasets/datasets.py.
 
More generally, the right transforms really depend on your application. The default transforms are good for cifar or imagenet but may not be good for other applications.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
